FROM python:3.12-slim

WORKDIR /opt/project

COPY docker/streaming/requirements.txt /tmp/requirements.txt

RUN pip install \
    --no-cache-dir \
    -r /tmp/requirements.txt

ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "src.streaming.consume_sales_events"]